{% extends 'base.phtml' %}
{% block content %}
<div class="barchart" data-chartdata="[32, 25, 79, 195, 56, 89, 100, 26]"></div>
<div class="barchart" data-chartdata="[2, 5, 5, 9,  24]"></div>
<div class="barchart" data-chartdata="[76, 85, 9, 24]"></div>
<div class="barchart" data-chartdata="[32, 25, 79, 200, 56, 89, 100, 24]"></div>
<div class="barchart" data-chartdata="[1, 2, 3, 4, 5, 6, 7, 8]"></div>

<style>
.barchart {
    display: flex;
    padding : 30px;
    border : 1px solid black;
}
.barchart + .barchart {
    margin-top : 20px;
}
.bar {
    flex: 1;
    align-self: flex-end;
    background-color : #ffb234;
    border : 1px solid #ff8d3b;
    opacity: .9;
    transition : opacity .5s;
    position: relative;
}
.bar + .bar {
    margin-left : 20px;
}
.bar:hover {
    cursor: pointer;
    opacity: 1;
}
.bar:hover::after {
    opacity: 1;
}
.bar::after {
    background : #99cccc;
    transition: opacity .5s;
    opacity: .1;
    text-align: center;
    color : white;
    padding : 5px;
    content : attr(data-label);
    display: block;
}
</style>

<script>
var normalise = function(array) {
    var normalised = [];
    min = Math.min(...array);//'spread' operator. wtf???
    max = Math.max(...array);
    for (var i = 0; i < array.length; i++) {
        value = array[i];
        normalised.push((value - min) / (max - min) + 1); //adding 1 so that I can multiply it by a value
    }
    return normalised;
};

//Set the height of each bar to be the chartdata
$('.barchart').each(function(){
    var that = this;
    var data = $(this).data('chartdata');
    var normalised = normalise(data);
    $.each(normalised, function(index, value){
        var bar = '<div class="bar" data-label="' + data[index] +'"></div>';
        $(that).append(bar);
        $.each($(that).find('.bar:eq(' + index + ')'), function(){
            $(this).height(value * 100);
        });
    });
});

</script>
{% endblock %}
