{% extends 'base.phtml' %}

{% block content %}

<div class="flex-row">

  <div class="component card">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>

  <div class="component card is-flipped">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>

  <div class="component card">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>
</div>

<div class="flex-row">
  <div class="component card">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>

  <div class="component card">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>
</div>

<div class="flex-row">
  <div class="component card">
    <img src="http://media4.popsugar-assets.com/files/2014/08/08/878/n/1922507/caef16ec354ca23b_thumb_temp_cover_file32304521407524949.xxxlarge/i/Funny-Cat-GIFs.jpg">
    <p>Look at this cat's face! Isn't it lovely? The answer is yes!</p>
  </div>
</div>

<style>
p {
  margin : 0;
  padding : 0;
}
.flex-row{
  display : flex;
}
.flex-row + .flex-row {
  margin-top : 5px;
}
.card {
  padding : 5px;
  font-size : 12px;
  display : flex;
  flex : 1;
  border : 1px solid #ccc;
  transition : border-color .5s;
}
.card img {
  width : 50px;
  height : 50px;
}
.card p {
  margin-left : 5px;
}
.card.is-flipped {
  flex-direction : row-reverse;
}
.card.is-flipped p {
  margin-left : 0;
}
.card.is-unavailable {
  opacity : 0.6;
  background : #ddd;
}
.card.is-error {
  border-color : red;
}
.card:hover {
  border-color : black;
  cursor : pointer;
}
.card + .card {
  margin-left : 5px;
}
</style>
{% endblock %}
