{% extends 'base.phtml' %}

{% block content %}
<form method="post">

  <div class="columns">
    <div class="column">
      <h2>Filesize
        <input type="radio" value="filesize" name="choice">
      </h2>
      <div class="columns">
          <div class="column">
            <input type="number" name="filesize" placeholder="filesize" min="1" max="999">
          </div>
          <div class="column">
            <select name="filesize-unit">
              <option value="bytes">b</option>
              <option value="kbytes">kb</option>
              <option value="mbytes">mb</option>
            </select>
          </div>
      </div>
    </div>

    <div class="column">
      <h2>Dimensions
        <input type="radio" value="dimensions" name="choice">
      </h2>
      <div class="columns">
          <div class="column">
            <input type="number" name="width" placeholder="width">
          </div>
          <div class="column">
            <input type="number" name="height" placeholder="height">
          </div>
      </div>
    </div>
  </div>


  <input type="submit">
</form>
{% endblock %}
