<html>
{% include 'head.phtml' %}
<body>
<main class="component">
  <section class="wrapper">
    <h1>Utilities and Examples</h1>
    <article class="example">
        <h1>PHP</h1>
        <p>Utilities I've made to make some things easier/quicker to do</p>
        <a href="util/rawtext">Raw text</a>
    </article>

    <article class="example">
        <h1>HTML CSS JS Experiments</h1>
        <p>Examples using modern CSS and HTML in place of JS (where possible).</p>
        <a href="snippets/barchart">barchart</a>
        <a href="snippets/component">component</a>
        <a href="snippets/datahotkey">datahotkey</a>
        <a href="snippets/filters">filters</a>
        <a href="snippets/inputs">input types</a>
        <a href="snippets/modals">modal popups</a>
        <a href="snippets/tabs">tabs</a>
        <a href="snippets/validation">validation</a>
    </article>
  </section>
</main>
{% include 'footer.phtml' %}
</body>
</html>
