<html>
{% include 'head.phtml' %}
<body>
<main>
  <section class="wrapper">
    <h1>Utilities and Examples</h1>
    <article class="example">
        <h1>PHP</h1>
        <p>Basic utilities I've made to make some things easier/quicker to do</p>
        <a href="utilities/photodata/">Photo data</a>
        <a href="utilities/webgrep/">Webgrep</a>
        <a href="util/imagemaker">Imagemaker</a>
    </article>

    <article class="example">
        <h1>HTML CSS JS Experiments</h1>
        <p>Simple examples using modern CSS and HTML in place of JS (where possible).</p>
        <a href="snippets/barchart">barchart</a>
        <a href="snippets/datahotkey">datahotkey</a>
        <a href="snippets/inputs">input types</a>
        <a href="snippets/modals">modal popups</a>
        <a href="snippets/slideshow">slideshow</a>
        <a href="snippets/tabs">tabs</a>
        <a href="snippets/validation">validation</a>
        <p>All source code is contained within each example. To reproduce an example all you have to do is copy and paste the page source and it should just work.</p>
    </article>
  </section>
</main>
</body>
</html>
