{% extends 'base.phtml' %}

{% block content %}
<p>There are loads of inputs. Learn them, use them.</p>

<div class="columns">
  <div class="column">
    <h3>Text</h3>
    <input type="text">
  </div>

  <div class="column">
    <h3>Email</h3>
    <input type="email">
  </div>
</div>

<div class="columns">
  <div class="column">
    <h3>Search</h3>
    <input type="search">
  </div>

  <div class="column">
    <h3>URL</h3>
    <input type="url">
  </div>
</div>

<h3>Password</h3>
<input type="password">

<h3>Number</h3>
<input type="number">

<h3>Range</h3>
<input type="range">

<h3>Colour</h3>
<input type="color">

<div class="columns">
  <div class="column">
    <h3>Datetime-local</h3>
    <input type="datetime-local">
  </div>
  <div class="column">
    <h3>Time</h3>
    <input type="time">
  </div>
</div>

<div class="columns">
  <div class="column">
    <h3>Date</h3>
    <input type="date">
  </div>
  <div class="column">
    <h3>Month</h3>
    <input type="month">
  </div>

  <div class="column">
    <h3>Week</h3>
    <input type="week">
  </div>
</div>






{% endblock %}
