{% extends 'base.phtml' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    <input name="file" type="file">
    <input type="submit">
</form>


<div class="image-container">
    <!--Omit unix directories '.' and '..'-->
    {% for image in images %}
        {{image}}
    {% endfor %}
    <?php foreach(array_diff(scandir('images'), ['.', '..']) as $file):?>
        <?php $file = "images/$file";?>
        <section>
            <?php $data = (exif_read_data($file, 0, true));?>
            <h1><?php echo htmlspecialchars($data['FILE']['FileName']);?></h1>
            <a href="<?php echo $file?>">
                <img src="<?php echo $file?>">
            </a>
            <h3>Data</h3>
            <div class="data">
                <?php foreach ($data as $key => $section):?>
                    <?php foreach ($section as $name => $value):?>
                        <p>
                          <span class="key"><?php echo $name?></span>:
                          <span class="value"><?php echo $value;?></span>
                        </p>
                    <?php endforeach;?>
                <?php endforeach;?>
            </div>
            <div href="#" class="delete-button">Delete</div>
        </section>
    <?php endforeach;?>
</div>

<script>
</script>
{% endblock %}


