{% extends 'base.phtml' %}
{% block content %}
<script src="{{script}}"></script>
<script src="{{sweetalertjs}}"></script>
<link rel="stylesheet" type="text/css" href="{{stylesheet}}">
<link rel="stylesheet" type="text/css" href="{{sweetalertcss}}">
<form method="post" enctype="multipart/form-data">
    <input name="file" type="file">
    <input type="submit">
</form>


<div class="image-container columns">
    {% for image in images %}
        <section class="column">
            <h1>{{image.filename}}</h1>
            <a href="/{{image.filename}}">
                <img src="/{{image.filename}}">
            </a>
            <h3>Data</h3>
            <div class="data">
                {% for key, section in image.exifData %}
                    {% for name, value in section %}
                        <p>
                            <span class="key"> {{name}}</span>
                            <span class="value"> {{value}}</span>
                        </p>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="delete-button">Delete</div>
        </section>
    {% endfor %}
</div>

<script>
</script>
{% endblock %}


