{% extends 'base.phtml' %}

{% block content %}
<div class="slides">
  <!--Try and use counter instead of slide num?-->
  <div class="slide current fatty" data-slide-num="1">
      <h1>Cats</h1>
      <img src="http://images.natureworldnews.com/data/images/full/15186/worried-cat.jpg"/>
  </div>

  <div class="slide fatty" data-slide-num="2">
      <h1>Dogs</h1>
      <img src="http://static.ddmcdn.com/gif/earliest-dogs-660x433-130306-akita-660x433.jpg"/>
  </div>

  <div class="slide-controls">
    <a href=# class="previous fatty">Previous</a>
    <a href=# class="next fatty">Next</a>
  </div>
</div>

<style>
.slides {
  height : 100vh;
  text-align: center;
  position: relative;
  overflow: hidden;
}
.slide {
  display : none;
  height : 90vh;
}
.slide-controls {
  position: absolute;
  bottom: 0;
  width : 100%;
  border-top: 1px solid #ccc;
}
.slide-controls a {
  min-width: 100px;
  margin : 25px;
  transition : background .5s, color .5s;
  border : 1px solid #ccc;
}
.slide-controls a:hover {
  background : #608ef7;
  color : white;
}
.next {
  float : right;
}
.previous {
  float : left;
}
.current {
  display : block;
}
.disabled {
  background : #ccc;
}
</style>

<script>
  var current = $('.current').data('slide-num');
  var slideNums = $('.slide').map(function(){
    return parseInt($(this).data('slide-num'));
  });
  var maxSlideNum = Math.max.apply(Math, slideNums);

  $('.slide-controls a').click(function(){
    $('.slide').removeClass('current');
    if ($(this).hasClass('next')) {
      current++;
    } else {
      current--;
    }
    if (current <= 0 || current > maxSlideNum) {
      current = maxSlideNum;
    }
    $('.slide[data-slide-num=' + current +']').addClass('current');
  });
</script>
{% endblock %}
