{% extends 'base.phtml' %}

{% block content %}
<form method="post">
  <h2>URL</h2>
  <input type="text" placeholder="www.domain.com">

  <h2>Search Term</h2>
  <input type="text" placeholder="Enter the string to search for">

  <label>
    <input type="checkbox">
    <span>recurse?</span>
  </label>

  <label>
    <input type="checkbox">
    <span>ignore search?</span>
  </label>

  <label>
    <input type="checkbox">
    <span>load ajax?</span>
  </label>

  <label>
    <input type="checkbox">
    <span>ignore HTML?</span>
  </label>

  <input type="submit">
</form>
{% endblock %}
